# Generated by Django 2.2.9 on 2021-03-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210305_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-pub_date']},
        ),
    ]
